import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminAuthRouter from "./admin-auth";
import adminPackagesRouter from "./admin-packages";
import adminTestimonialsRouter from "./admin-testimonials";
import adminBookingsRouter from "./admin-bookings";
import adminSettingsRouter from "./admin-settings";
import adminRewardsRouter from "./admin-rewards";
import publicPackagesRouter from "./public-packages";
import publicBookingsRouter from "./public-bookings";
import publicTestimonialsRouter from "./public-testimonials";
import storageRouter from "./storage";
import adminGalleryRouter from "./admin-gallery";
import publicGalleryRouter from "./public-gallery";
import categoriesRouter from "./admin-categories";
import servicesRouter from "./services";
import heroSlidesRouter from "./admin-hero-slides";
import fsUploadRouter from "./fs-upload";
import pushRouter from "./push";
import whyUsRouter from "./why-us";
import aiChatRouter from "./ai-chat";
import ticketsRouter from "./tickets";
import shareScanRouter from "./share-scan";
import adminAuditRouter from "./admin-audit";
import adminPromoCodesRouter from "./admin-promo-codes";
import adminReviewsRouter from "./admin-reviews";
import adminWaitlistRouter from "./admin-waitlist";
import adminCapacityRouter from "./admin-capacity";
import adminUsersRouter from "./admin-users";
import adminAbandonedCartsRouter from "./admin-abandoned-carts";
import customerPhotosRouter from "./customer-photos";
import aiQuizRouter from "./ai-quiz";
import adminManualTicketsRouter from "./admin-manual-tickets";
import { authMiddleware } from "../middleware/auth";
import { requireAdminApiPermission } from "../lib/adminPermissions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminAuthRouter);
router.use("/admin", authMiddleware, requireAdminApiPermission);
router.use(adminPackagesRouter);
router.use(adminTestimonialsRouter);
router.use(adminBookingsRouter);
router.use(adminManualTicketsRouter);
router.use(adminSettingsRouter);
router.use(adminRewardsRouter);
router.use(publicPackagesRouter);
router.use(publicBookingsRouter);
router.use(publicTestimonialsRouter);
router.use(storageRouter);
router.use(adminGalleryRouter);
router.use(publicGalleryRouter);
router.use(categoriesRouter);
router.use(servicesRouter);
router.use(heroSlidesRouter);
router.use(fsUploadRouter);
router.use(pushRouter);
router.use(whyUsRouter);
router.use(aiChatRouter);
router.use(ticketsRouter);
router.use(shareScanRouter);
router.use(adminAuditRouter);
router.use(adminPromoCodesRouter);
router.use(adminReviewsRouter);
router.use(adminWaitlistRouter);
router.use(adminCapacityRouter);
router.use(adminUsersRouter);
router.use(adminAbandonedCartsRouter);
router.use(customerPhotosRouter);
router.use(aiQuizRouter);

export default router;
