import { pgTable, serial, text, integer, real, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const packages = pgTable("packages", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  icon: text("icon").notNull().default("🏖️"),
  titleAr: text("title_ar").notNull(),
  titleEn: text("title_en").notNull(),
  descriptionAr: text("description_ar").notNull().default(""),
  descriptionEn: text("description_en").notNull().default(""),
  longDescriptionAr: text("long_description_ar").notNull().default(""),
  longDescriptionEn: text("long_description_en").notNull().default(""),
  category: text("category").notNull().default("safari"),
  priceEGP: integer("price_egp").notNull().default(0),
  maxPriceEGP: integer("max_price_egp").notNull().default(0),
  durationAr: text("duration_ar").notNull().default(""),
  durationEn: text("duration_en").notNull().default(""),
  color: text("color").notNull().default("#00AAFF"),
  badgeAr: text("badge_ar"),
  badgeEn: text("badge_en"),
  badgeColor: text("badge_color"),
  featured: boolean("featured").notNull().default(false),
  popular: boolean("popular").notNull().default(false),
  familyFriendly: boolean("family_friendly").notNull().default(false),
  foreignerFriendly: boolean("foreigner_friendly").notNull().default(false),
  childrenFriendly: boolean("children_friendly").notNull().default(false),
  experienceLevel: text("experience_level").notNull().default("easy"),
  rating: real("rating").notNull().default(4.5),
  reviewCount: integer("review_count").notNull().default(0),
  images: jsonb("images").$type<string[]>().notNull().default([]),
  includesAr: jsonb("includes_ar").$type<string[]>().notNull().default([]),
  includesEn: jsonb("includes_en").$type<string[]>().notNull().default([]),
  excludesAr: jsonb("excludes_ar").$type<string[]>().notNull().default([]),
  excludesEn: jsonb("excludes_en").$type<string[]>().notNull().default([]),
  itineraryAr: jsonb("itinerary_ar").$type<{title:string;desc:string}[]>().notNull().default([]),
  itineraryEn: jsonb("itinerary_en").$type<{title:string;desc:string}[]>().notNull().default([]),
  whyThisTripAr: jsonb("why_this_trip_ar").$type<{icon:string;text:string}[]>().notNull().default([]),
  whyThisTripEn: jsonb("why_this_trip_en").$type<{icon:string;text:string}[]>().notNull().default([]),
  suitableFor: jsonb("suitable_for").$type<string[]>().notNull().default([]),
  whatToBringAr: jsonb("what_to_bring_ar").$type<string[]>().notNull().default([]),
  whatToBringEn: jsonb("what_to_bring_en").$type<string[]>().notNull().default([]),
  cancellationAr: text("cancellation_ar").notNull().default(""),
  cancellationEn: text("cancellation_en").notNull().default(""),
  faq: jsonb("faq").$type<{questionAr:string;questionEn:string;answerAr:string;answerEn:string}[]>().notNull().default([]),
  similarIds: jsonb("similar_ids").$type<number[]>().notNull().default([]),
  includesMeals: boolean("includes_meals").notNull().default(false),
  includesTransport: boolean("includes_transport").notNull().default(false),
  includesAccommodation: boolean("includes_accommodation").notNull().default(false),
  minGroupSize: integer("min_group_size").notNull().default(1),
  maxGroupSize: integer("max_group_size").notNull().default(20),
  active: boolean("active").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertPackageSchema = createInsertSchema(packages).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertPackage = z.infer<typeof insertPackageSchema>;
export type Package = typeof packages.$inferSelect;
